Sprint4
OlegMzhelskiy/url-shortener pull request #5
Opened 2022-07-18 19:21 UTC by OlegMzhelskiy

2022-07-20 18:43 UTC, sergeysergeevru requested changes
Привет) Смотрится хорошо, давай сделаем проверку линтером зеленой и вообще огонь будет. Спасибо!)

2022-07-20 18:43 UTC, sergeysergeevru commented on storage/postgre.go
> +	makeDelStmt, _ := db.Prepare("UPDATE urls SET deleted = true WHERE short_url = $1")
ошибки важно проверять https://github.com/golang/go/wiki/CodeReviewComments#handle-errors

2022-07-20 18:43 UTC, sergeysergeevru commented on storage/postgre.go
> +	//err := store.db.QueryRowContext(ctx, "SELECT origin_url, deleted FROM urls WHERE short_url = $1 LIMIT 1", id).Scan(&orig, &del)
давай оставлять код чистым) Ненужные куски кода лучше удалить, тогда проще ориентироваться по проекту во время поиска

2022-07-20 18:43 UTC, sergeysergeevru commented on storage/postgre.go
> +func (store StoreDB) GetUserMapURLs(ctx context.Context, UserID string) map[string]string {
я бы предпочел иметь метод следующей сигнатуры, допустим:
```go
func (store StoreDB) GetUrlsByUserId(ctx context.Context, UserID string) ([]PairURL, error) {
```
тогда мы можем получать слайс с полной информацией которая хранится в базе для пользователя. Возврат мапы в текущем случае усложнаяет масштабирование в будущем, если нам понадобятся еще какие либо данные. С точки зрения базы в общем случае, вытаскивание всех полей будет одинаково по трудозатратам как и двух полей.

2022-07-20 18:43 UTC, sergeysergeevru commented on storage/postgre.go
> +			return err
тут мы вернем nil выше если вдруг придется выполнить rollback. Это достаточно критично, ибо логика выше решит, что все сохранилось успешно

2022-07-20 18:43 UTC, sergeysergeevru commented on storage/postgre.go
> +	}
здесь и далее стоит возвращать ошибку выше. Мы же должны сигнализировать клиенту о проблемах

2022-07-20 18:43 UTC, sergeysergeevru commented on pkg/handler/handler.go
> +		}
Теоретически можно тоже унести в асинхронную обработку,  ибо по заданию у нас нет обязанности отвечать ошибкой если ссылки не принадлежат пользователю. Тогда ручка будет отвечать еще быстрее)

2022-07-20 21:44 UTC, OlegMzhelskiy commented on storage/postgre.go
> +func (store StoreDB) GetUserMapURLs(ctx context.Context, UserID string) map[string]string {
есть метод с похожей сигнатурой GetUserURLs(ctx context.Context, UserID string) []PairURL (добавлю ошибку в качестве 2-го возвращаемого параметра)

а этот GetUserMapURLs метод конкретно нужен чтобы быстро проверить существование short_url у конкретного пользователя, не обходя каждый раз весь слайс в цикле для поиска (для этого возвращаю как раз мапу)

2022-07-25 10:04 UTC, sergeysergeevru approved these changes
Отлично, спасибо за исправления!

2022-07-26 20:14 UTC, merged